version: '3.8'

services:
  # NestJS Backend Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: shiftify-backend-prod
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Angular Frontend Service
  frontend:
    build:
      context: . 
      dockerfile: frontend/Dockerfile 
    container_name: shiftify-frontend-prod
    ports:
      - "8080:80"
    restart: unless-stopped
    